# Generated by Django 3.0.7 on 2020-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dakhl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mizan', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('darayi', models.BigIntegerField()),
            ],
        ),
    ]
