# Generated by Django 3.0.7 on 2020-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dakhl',
            name='tozih',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
