# Generated by Django 3.0.7 on 2020-06-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dakhl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dakhl',
            name='dolar',
            field=models.BigIntegerField(null=True),
        ),
    ]
