# Generated by Django 3.0.7 on 2020-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_dakhl_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dakhl',
            name='mizan_dolar',
            field=models.IntegerField(null=True),
        ),
    ]
