# Generated by Django 4.0.4 on 2023-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_dakhl_mizan_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakhl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
